# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubevigil < Formula
  desc "Kubernetes Security Posture Management CLI — know your clusters before attackers do."
  homepage "https://github.com/stribog-cloud/KubeVigil"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stribog-cloud/KubeVigil/releases/download/v1.1.0/kubevigil_1.1.0_darwin_amd64.tar.gz"
      sha256 "1c2e4e8ca7aa11d235aa4175c162282a3860d3ca35eeff219633e51a69c5aa04"

      define_method(:install) do
        bin.install "kubevigil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stribog-cloud/KubeVigil/releases/download/v1.1.0/kubevigil_1.1.0_darwin_arm64.tar.gz"
      sha256 "af556811f4dc3c343e86fc58cd0227858e28cb3f8db47bd28d0a9d4341c60d0b"

      define_method(:install) do
        bin.install "kubevigil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stribog-cloud/KubeVigil/releases/download/v1.1.0/kubevigil_1.1.0_linux_amd64.tar.gz"
      sha256 "6c2b7452f370f1eb90c5c0998aef44f6ebe0f074ffa8ec229eed5802b649d87f"
      define_method(:install) do
        bin.install "kubevigil"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stribog-cloud/KubeVigil/releases/download/v1.1.0/kubevigil_1.1.0_linux_arm64.tar.gz"
      sha256 "873692ba52496d45e4aa4271d1d596846145e0eacea731280ece525c99267d9d"
      define_method(:install) do
        bin.install "kubevigil"
      end
    end
  end

  test do
    system "#{bin}/kubevigil", "version"
  end
end
